
export const TYPE = {
    LOADING_START:'LOADING_START',
    LOADING_END:'LOADING_END',

    GET_TOKEN:'GET_TOKEN',
    SAVE_TOKEN:'SAVE_TOKEN',
    REMOVE_TOKEN:'REMOVE_TOKEN',

    GET_REFRESH_TOKEN:'GET_REFRESH_TOKEN',
    SAVE_REFRESH_TOKEN:'SAVE_REFRESH_TOKEN',
    REMOVE_REFRESH_TOKEN:'REMOVE_REFRESH_TOKEN',

    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SYNC: 'FETCH_USERS_SYNC',

    FETCH_AUTH_SUCCESS: 'FETCH_AUTH_SUCCESS',
    FETCH_AUTH_FAILURE: 'FETCH_AUTH_FAILURE',
    FETCH_AUTH_REMOVE: 'FETCH_AUTH_REMOVE',

    ERROR:'ERROR'
};
export const SYNC = {
  USERS:3600,
  AUTH:60,
  HISTORY:300
};
