
export const TYPE = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SYNC: 'FETCH_USERS_SYNC',

    FETCH_LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
    FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
    FETCH_LOGIN_SYNC: 'FETCH_LOGIN_SYNC'
};
export const SYNC = {
  USERS:3600,
  AUTH:60,
  HISTORY:300
};
