export const TYPE = {
    LOADING_START: 'LOADING_START',
    LOADING_END: 'LOADING_END',

    GET_TOKEN: 'GET_TOKEN',
    SAVE_TOKEN: 'SAVE_TOKEN',
    REMOVE_TOKEN: 'REMOVE_TOKEN',

    GET_REFRESH_TOKEN: 'GET_REFRESH_TOKEN',
    SAVE_REFRESH_TOKEN: 'SAVE_REFRESH_TOKEN',
    REMOVE_REFRESH_TOKEN: 'REMOVE_REFRESH_TOKEN',

    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    FETCH_USERS_SYNC: 'FETCH_USERS_SYNC',

    FETCH_AUTH_SUCCESS: 'FETCH_AUTH_SUCCESS',
    FETCH_AUTH_FAILURE: 'FETCH_AUTH_FAILURE',
    FETCH_AUTH_REMOVE: 'FETCH_AUTH_REMOVE',

    SET_TRIP_TYPE:'SET_TRIP_TYPE',

    ERROR: 'ERROR'
};
export const SYNC = {
    USERS: 3600,
    AUTH: 60,
    HISTORY: 300
};

export const TRIP = {
    ONE_WAY: 'One Way',
    ROUND_TRIP: 'Round Trip',
    MULTI_DESTINATION: 'Multi Destination',
};

export const CABIN = {
    BUSINESS: 'Business',
    ECONOMY: 'Economy',
    FIRST_CLASS: 'First Class',
};
